### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by rpkarlsson** [JuliaSivartsson/laboration3-angular.1dv450#1]
Hej.

Har klickat runt i din applikation och kikat på din kod och tycker det ser väldigt trevligt ut. All funktionalitet verkar vara på plats och validering av indata fungerar bra.
Bra tydlig dokumentation som gjorde min review väldigt lätt att utföra.
Har väldigt svårt att hitta några issues värda att kommentera. Men bara för att få något så kan jag nämna att jag hittade ett ganska stort block med kommenterad kod och kan nog känna att många av dina kommenterar känns i stort sett överflödiga då du uttrycker flödet i koden med väldigt bra namngivning vilket gör att kommentarerna i stort sätt upprepar koden. Dessa två saker var det enda jag reagerade på.
Du hör ju lite vad jag får dra fram bara för att kommentera något här...

Tycker det var välskriven kod som var intressant att gå igenom. Även roligt att få se dina lösningar på problem jag känner igen i från min egna applikation.

/Robin

**Comment by rpkarlsson** [comment]
En fundering om man får vara nyfiken?
Hur kommer det sig att dina controllers heter ...ViewModel?
Har inte stött på detta i andra angular projekt så blev lite nyfiken på anledningen till detta.

**Comment by JuliaSivartsson** [comment]
Tack för kommentarerna :) Tänkte bara nämna varför jag valt att döpa dem till ViewModels, vi har använt angular i andra kursen (1dv411) och där följde vi flera guider där de nämner att controllers egentligen är ett lager mellan vyn och factory, så de blir som en slags vymodell i många avseenden, det fastnade hos mig och därför fick de heta så :)
